# Generated by Django 5.1.7 on 2025-03-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
