# Generated by Django 5.1.7 on 2025-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_remove_doctor_email_remove_doctor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='paitent_meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
